server {
    listen 80;
    server_name dscc-15751-wiut.duckdns.org;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name dscc-15751-wiut.duckdns.org;

    ssl_certificate /etc/letsencrypt/live/dscc-15751-wiut.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/dscc-15751-wiut.duckdns.org/privkey.pem;

    location /static/ {
        alias /app/staticfiles/;
    }

    location /media/ {
        alias /app/media/;
    }

    location / {
        proxy_pass http://web:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
